### ISSUE TITLE
Add a template

### ISSUE THREAD

**Issue by ADI10HERO** [ADI10HERO/adi10hero.github.io#1]
A good template to start with : https://html5up.net/stellar

**Comment by oneamanish** [comment]
see my pull req.

**Comment by ADI10HERO** [comment]
Hey @oneamanish

By template, I meant something with the whole package: HTML, CSS, JS.
Ofc you won't know the details so filling John Doe and Loerm Ispum for text would be fine.

Also I'd really really appreciate some screen shots in the PR so I know what it's supposed to look like!

Thanks!

**Comment by ADI10HERO** [comment]
@oneamanish Are you still interested in the PR?
